const C = {
  ADD_MESSAGE: "ADD_MESSAGE",
  ADD_MESSAGES: "ADD_MESSAGES",
  TOGGLE_THING: "TOGGLE_THING",
  UPDATE_ALL_THINGS: "UPDATE_ALL_THINGS",
  UPDATE_CONNECTIONS: "UPDATE_CONNECTIONS",
  UPDATE_SYSTEMS: "UPDATE_SYSTEMS",
  UPDATE_SYSTEM: "UPDATE_SYSTEM",
  UPDATE_THINGS: "UPDATE_THINGS",
  
  SYSTEM_CONNECTED: "SYSTEM_CONNECTED",
  SYSTEM_DISCONNECTED: "SYSTEM_DISCONNECTED",

  UPDATE_DEVICES: "UPDATE_DEVICES",
  ADD_DEVICE: "ADD_DEVICE",
  UPDATE_DEVICE: "UPDATE_DEVICE",
  REMOVE_DEVICE: "REMOVE_DEVICE",
  
  UPDATE_ITEMS: "UPDATE_ITEMS",
  ADD_ITEM: "ADD_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",

  UPDATE_DEVICE_SETTINGS: "UPDATE_DEVICE_SETTINGS",
  UPDATE_ITEM_SETTINGS: "UPDATE_ITEM_SETTINGS",

  UPDATE_DICTIONARY: "UPDATE_DICTIONARY",

  THING_ONLINE: "THING_ONLINE",
  THING_OFFLINE: "THING_OFFLINE",
  ITEM_CHANGE_STATE: "ITEM_CHANGE_STATE",
  ITEM_CHANGE_VALUE: "ITEM_CHANGE_VALUE",
  METHOD_CHANGE_STATE: "METHOD_CHANGE_STATE",
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
  ADD_TOKEN: "ADD_TOKEN",
  REMOVE_TOKEN: "REMOVE_TOKEN",
  QUIT: "QUIT"
}
export default C